Remove setTempRet0, getTempRet0 from WASM_SYSTEM_EXPORTS
This change allows more dynamic linking tests to build and run with
MAIN_MODULE=2 rather than MAIN_MODULE=2.

Some background: `setTempRet0` and `getTempRet0` are a little odd
because they exist bot as runtime functions accessible from JS as
`setTempRet0` and `getTempRet0` but also as library functions accessible
as `_getTempRet0` and `_getTempRet0`.

More background: I believe WASM_SYSTEM_EXPORTS is designed to allow
certain symbols to be exported *from* wasm without mangling.  However,
these two symbols are always defined in JS and never defined in wasm so I
don't believe they ever belonged in this list.

The problem with these symbol being lists in WASM_SYSTEM_EXPORTS was
manifesting itself as:

  RuntimeError: abort('getTempRet0' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)) at Error

By removing these two symbols from the WASM_SYSTEM_EXPORTS the symbols
will be bound to the library forms of these symbols instead, which
does work and which take part in the symbol resolution process.